### PR TITLE
Simplify development environment with docker-compose

### PR DESCRIPTION
**Pull request by brainstorm**
Hello @rcurrie, fantastic project initiative.

I'll be exploring working a bit on this app, bear with me while I find issues and try to correct them as I go ;)

@ohofmann

### CODE REVIEW

**Comment by brainstorm** [comment]
I'll be looking at better debugging/reload next after this PR gets merged, something like:

https://stackoverflow.com/questions/8831748/how-to-set-up-autoreload-with-flaskuwsgi

I got the following backtrace when connecting to `http://localhost:5000`, will look into that tomorrow:

```
cgtd_1  | ERROR:cgtd.cgtd:Exception on /v0/stewards [GET]
cgtd_1  | Traceback (most recent call last):
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
cgtd_1  |     rv = self.dispatch_request()
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
cgtd_1  |     return self.view_functions[rule.endpoint](**req.view_args)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 309, in wrapper
cgtd_1  |     resp = resource(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
cgtd_1  |     return self.dispatch_request(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
cgtd_1  |     resp = meth(*args, **kwargs)
cgtd_1  |   File "./cgtd/cgtd.py", line 214, in get
cgtd_1  |     us = get_steward()
cgtd_1  |   File "./cgtd/cgtd.py", line 80, in get_steward
cgtd_1  |     return json.loads(g.ipfs.cat(resolve_steward(address)))
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/client.py", line 126, in cat
cgtd_1  |     return self._cat.request(self._client, multihash, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/commands.py", line 31, in request
cgtd_1  |     return client.request(self.path, args=args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 25, in wrapper
cgtd_1  |     return f(self, *args, **merged)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 101, in request
cgtd_1  |     raise ipfsApiError(ret['Message'])
cgtd_1  | TypeError: string indices must be integers
```

**Comment by ohofmann** [comment]
Yay. Excited already ;)

**Comment by rcurrie** [comment]
With respect to auto reload, make debug started uwsgi with reloading turned on. docker-compose would be nicer then the make approach I have taken but ideally would like a way to start in debug or normal mode.

**Comment by brainstorm** [comment]
@rcurrie, that's precisely my plan for today, figure out a comfortable reload mode for `make debug` and uwsgi/flask, so please don't merge this PR just yet ;)

**Comment by brainstorm** [comment]
Added back the `make debug` convenience target. The backtrace above was caused by not running `make reset` (perhaps we should add it on `start`?).

Anyways, this should be mergeable right now as it is, imho.

**Comment by rcurrie** [comment]
calling open http://... doesn't work if you're doing development on a remote server - that's really a client thing and for the most part the cgtd is just a REST server - the gui is purely for demo purposes. Wrt make debug it seems a bit clunky to mix it with docker compose as 'down' stops ipfs as well. Maybe two docker compose files with one for debug?

**Comment by brainstorm** [comment]
Gotcha on the `open` Makefile trick. I thought it would ease/simplify the local dev work (and fail without much fuss on remote systems), but can also be considered intrusive, so I'll remove it.

Regarding **debug**, I'm not entirely happy with my solution neither yours since in your case it requires extra flags passed to `docker-compose` to account for the two different modes.

It feels like the easiest, perhaps also most adopted when searching around, would be to export `FLASK_DEBUG=1` environment variable or similar in the host and act accordingly in the container.

Makes sense?

**Comment by rcurrie** [comment]
I don’t think FLASK_DEBUG will work with uwsgi as its uwsgi doing the auto-reloading. If it does that that sounds like a good solution.

**Comment by rcurrie** [comment]
Aha! The string conflict due to ipfs updating their api. I've pushed a fix (remove [1] from the return of add). Still need to sort what the cleanest way to use docker-compose so we retain debug reload.

**Comment by brainstorm** [comment]
Rob, regarding your concerns about `FLASK_DEBUG=1` and uwsgi, I found this:

https://codeseekah.com/2012/10/28/dubugging-flask-applications-under-uwsgi/

And I've been thinking to get to something similar to this:

https://blog.docker.com/2016/07/live-debugging-docker/

Not so tight integration with IDE's is needed but something that is more practical to debug than now.

I also applied your latest changes (in https://github.com/ga4gh/CGT/commit/f9107af06221) and found that the same error persists, plus a couple of (perhaps just spurious) IPFS errors:

```
ipfs_1  | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1  | Daemon is ready
ipfs_1  | 10:31:03.688 ERROR        dht: no addresses on peer being sent!
ipfs_1  | 					[local:<peer.ID a5kUDB>]
ipfs_1  | 					[sending:<peer.ID eQGvYh>]
ipfs_1  | 					[remote:<peer.ID SoLju6>] handlers.go:75
ipfs_1  | 10:31:19.926 ERROR        dht: no addresses on peer being sent!
ipfs_1  | 					[local:<peer.ID a5kUDB>]
ipfs_1  | 					[sending:<peer.ID eQGvYh>]
ipfs_1  | 					[remote:<peer.ID SoLju6>] handlers.go:75
cgtd_1  | [pid: 13|app: 0|req: 1/1] 172.18.0.1 () {34 vars in 690 bytes} [Mon Aug 15 10:31:22 2016] GET / => generated 3069 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
cgtd_1  | INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ipfs
cgtd_1  | DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v0/id?stream-channels=true&encoding=json HTTP/1.1" 200 None
cgtd_1  | DEBUG:root:Resolving Qma5kUDBtt3ybYya4M3PccRsa1Jx4C4toYnMTnqT7ZJHvA...
cgtd_1  | INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ipfs
cgtd_1  | DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v0/id?stream-channels=true&encoding=json HTTP/1.1" 200 None
cgtd_1  | INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ipfs
cgtd_1  | DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v0/name/resolve?stream-channels=true&local=True&arg=Qma5kUDBtt3ybYya4M3PccRsa1Jx4C4toYnMTnqT7ZJHvA HTTP/1.1" 200 None
cgtd_1  | DEBUG:root:... to QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
cgtd_1  | INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ipfs
cgtd_1  | DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v0/cat?stream-channels=true&encoding=json&arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn HTTP/1.1" 500 None
cgtd_1  | [2016-08-15 10:31:22,886] ERROR in app: Exception on /v0/stewards [GET]
cgtd_1  | Traceback (most recent call last):
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
cgtd_1  |     rv = self.dispatch_request()
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
cgtd_1  |     return self.view_functions[rule.endpoint](**req.view_args)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 309, in wrapper
cgtd_1  |     resp = resource(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
cgtd_1  |     return self.dispatch_request(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
cgtd_1  |     resp = meth(*args, **kwargs)
cgtd_1  |   File "./cgtd/cgtd.py", line 214, in get
cgtd_1  |     us = get_steward()
cgtd_1  |   File "./cgtd/cgtd.py", line 80, in get_steward
cgtd_1  |     return json.loads(g.ipfs.cat(resolve_steward(address)))
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/client.py", line 126, in cat
cgtd_1  |     return self._cat.request(self._client, multihash, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/commands.py", line 31, in request
cgtd_1  |     return client.request(self.path, args=args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 25, in wrapper
cgtd_1  |     return f(self, *args, **merged)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 101, in request
cgtd_1  |     raise ipfsApiError(ret['Message'])
cgtd_1  | TypeError: string indices must be integers
cgtd_1  | ERROR:cgtd.cgtd:Exception on /v0/stewards [GET]
cgtd_1  | Traceback (most recent call last):
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
cgtd_1  |     rv = self.dispatch_request()
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
cgtd_1  |     return self.view_functions[rule.endpoint](**req.view_args)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 309, in wrapper
cgtd_1  |     resp = resource(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
cgtd_1  |     return self.dispatch_request(*args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
cgtd_1  |     resp = meth(*args, **kwargs)
cgtd_1  |   File "./cgtd/cgtd.py", line 214, in get
cgtd_1  |     us = get_steward()
cgtd_1  |   File "./cgtd/cgtd.py", line 80, in get_steward
cgtd_1  |     return json.loads(g.ipfs.cat(resolve_steward(address)))
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/client.py", line 126, in cat
cgtd_1  |     return self._cat.request(self._client, multihash, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/commands.py", line 31, in request
cgtd_1  |     return client.request(self.path, args=args, **kwargs)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 25, in wrapper
cgtd_1  |     return f(self, *args, **merged)
cgtd_1  |   File "/usr/lib/python2.7/site-packages/ipfsApi/http.py", line 101, in request
cgtd_1  |     raise ipfsApiError(ret['Message'])
cgtd_1  | TypeError: string indices must be integers
cgtd_1  | [pid: 14|app: 0|req: 1/2] 172.18.0.1 () {36 vars in 726 bytes} [Mon Aug 15 10:31:22 2016] GET /v0/stewards => generated 37 bytes in 90 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
ipfs_1  | 10:31:31.415 ERROR        dht: no addresses on peer being sent!
ipfs_1  | 					[local:<peer.ID a5kUDB>]
ipfs_1  | 					[sending:<peer.ID eQGvYh>]
ipfs_1  | 					[remote:<peer.ID SoLju6>] handlers.go:75
ipfs_1  | 10:31:40.631 ERROR        dht: no addresses on peer being sent!
ipfs_1  | 					[local:<peer.ID a5kUDB>]
ipfs_1  | 					[sending:<peer.ID eQGvYh>]
ipfs_1  | 					[remote:<peer.ID SoLueR>] handlers.go:75
```

**Comment by rcurrie** [comment]
I tried out the latest, looking good but a few things I think we should sort (though they may be operator error):

--network in makefile isn't a docker option, should be --net=

make debug leaves the existing production cgtd running against the same ipfs instance that the debug one is running against. As the test is destructive this might cause some unwanted side affects.

I was unable to contact the debug instance on port 3000. Will look a bit closer but we may just want two docker-compose files that tilt up totally separate nodes including ipfs.

Wrt uwsgi I think some sort of environment variable to turn on debugging 

Finally a nit but I run all code through PEP8 on each save, would like to try and keep this repo compliant - its just easier if someone is used to the mental view or most python library code.

**Comment by rcurrie** [comment]
Tried out the latest:

make reset should be:

docker-compose exec ipfs sh -c "echo '{\"domain\": \"cgt.lorem.edu\", \"submissions\": [], \"peers\": []}' | ipfs add -q | xargs ipfs name publish"

uwsgi.ini should stay with multiple processes and threads as that's needed for a production server given how long ipns can take sometimes. You can override these on the command line for debug

I like the docker-compose style but still struggle as to how we can map the local folder for edit/reload behavior. I think the options are either a separate compose file or just a make option that starts up a debug cgtd with an explicit run command.

Should add a build: . to the docker compose

Seems like we 'might' want to have ipfs store in a data volume so that it isn't empty on every launch for production.

**Comment by brainstorm** [comment]
Thanks @rcurrie for the review and lay down the points we discussed last week during the call.

Just reverted the changes as you pointed and started to go down the `docker-compose-debug.yml` route, still not convinced, but couldn't find better alternatives yet. Still need to wire up that `-debug.yml` with the rest of the app since it uses `PORT+1` scheme so that it does effectively separate from production instances, hang on).

Regarding the `make reset` line, I switched to docker-compose `run` instead of docker-compose `exec` since the latter seems to be deprecated in later `docker-compose` releases:

https://docs.docker.com/compose/reference/

I'll keep it at `exec` for now since it still works on docker-compose 1.8.0, but I hope it doesn't break in the near future :-S

Regarding the edit/reload behavior, I added a `setup.py` so that one can do `pip install -e .` (a.k.a `python setup.py develop`), which allows for easy python in-place edits and should remove the need for the `update_pip_packages` and `update_requirements` Makefile targets once we get used to it.

Sorry for not explaining those changes/tests a bit more in detail as I go, will try to be better at that in the future... experimental stuff over here (for me included).

PD: Been looking into remote python debugging, so that one can simply attach to the running container from outside, with varying degrees of ~~success~~ failure so far:

https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging
https://pypi.python.org/pypi/pydevd
https://pypi.python.org/pypi/rpdb/0.1.6

**Comment by brainstorm** [comment]
Btw, the official `ipfs-go` usage manual seems to use docker volumes (`-v`) for IPFS data and staging:

```
docker run -d --name ipfs_host -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 8080:8080 -p 4001:4001 -p 5001:5001 ipfs/go-ipfs:latest
```

https://github.com/ipfs/go-ipfs#usage

**Comment by rcurrie** [comment]
The current Makefile does that but using a local folder (data). I think we should use it as it will mean debug and normal compose can use the same ipfs database.

**Comment by rcurrie** [comment]
Aha - didn’t know that about exec being deprecated. By all means keep it at run then.

**Comment by rcurrie** [comment]
Having trouble getting 'docker-compose up' to work - the ipfs container always exists with:
ipfs_1  | Error: no ipfs repo found in /data/ipfs
yet when started directly via 'docker-compose run ipfs' it works fine. There must be some subtle difference between those that the init script in ipfs doesn't like.
Does straing 'docker-compose up' work for you?

**Comment by brainstorm** [comment]
Just tried with plain `docker-compose up` and all gets instantiated correctly:

```
ipfs_1  | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1  | Swarm listening on /ip4/172.19.0.2/tcp/4001
ipfs_1  | Swarm listening on /ip6/::1/tcp/4001
ipfs_1  | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1  | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1  | Daemon is ready
```

I cannot stress more the need to have the **latest docker versions/environment**, it really affects a lot when working with docker in my experience, here are mine:

```
mba-3:cgtd romanvg$ docker --version
Docker version 1.12.1, build 23cf638, experimental
mba-3:cgtd romanvg$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```

**Comment by brainstorm** [comment]
@rcurrie, I might have to take it back, [TravisCI is showing some issues too](https://travis-ci.org/brainstorm/CGT/builds/155962003#L410), interesting:

```
$ make reset
# Reset steward to no submissions and no peers and then gc
docker-compose exec ipfs sh -c "echo '{\"domain\": \"cgt.lorem.edu\", \"submissions\": [], \"peers\": []}' | ipfs add -q | xargs ipfs name publish"
ERROR: No container found for ipfs_1
make: *** [reset] Error 1
```

Chasing that now...

**Comment by rcurrie** [comment]
Hmmm…I’m still getting errors. Can you try but make sure you have a clean ipfs data directory first (if ipfs ran before successfully you may have already initialized a volume):

docker-compose rm --al
docker pull ipfs/go-ipfs:latest
docker-compose up

I always get ipfs complaining about not being initialized with this sequence vs. run.

**Comment by rcurrie** [comment]
I've tried running ipfs a few versions back with the same behavior of ipfs not initializing a blank repo. Its not a docker-compose issue as running with -it initializes the repo while -d complains about an empty repo. Reading through https://github.com/ipfs/go-ipfs/blob/master/bin/container_daemon I have no idea why ipfs init is not being called. This must relate to a docker update though vs. any change in ipfs.

**Comment by rcurrie** [comment]
AH HAH! ipfs init fails if there is no stdin:
https://github.com/ipfs/go-ipfs/issues/2748
This explains why run works with -it but as a daemon or in compose it fails...still need to sort how we work around or when it will be resolved in a dockerized ipfs build

**Comment by rcurrie** [comment]
Lots of good work here and I'm excited to integrate it once its stabilized but we may want to take a more incremental approach to the current repo (first switch to compose, then travis etc...). Also might suggest we pause on tool/configuration changes until after GA4GH and focus on getting servers and demos up.

**Comment by brainstorm** [comment]
Gotcha @rcurrie, one problem with Travis is that the actual tests do not pass yet for me (neither locally nor in travis). Did you run `make tests` lately in your local setup? Does it pass all tests?

**Pull request closed without merging**
